version: 2.1 
jobs: 
  build: 
    working_directory: ~/example-auditjs-repo 
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm i
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run auditjs
          command: npx auditjs@beta ossi --xml > reports/dependency-results.xml
      - store_artifacts:
          path: reports
          prefix: dependencies
      - store_test_results:
          path: reports
